// Auto-generated by the generate command. Do not edit manually.
import type { FC, SVGProps } from 'react';

type SvgComponent = FC<SVGProps<SVGSVGElement>>;

import _0 from '../../output/svg/0.tsx';
import _1 from '../../output/svg/1.tsx';
import _2 from '../../output/svg/2.tsx';
import _3 from '../../output/svg/3.tsx';
import _4 from '../../output/svg/4.tsx';
import _5 from '../../output/svg/5.tsx';
import _6 from '../../output/svg/6.tsx';
import _7 from '../../output/svg/7.tsx';
import _8 from '../../output/svg/8.tsx';
import _9 from '../../output/svg/9.tsx';
import _36 from '../../output/svg/a.tsx';
import _37 from '../../output/svg/b.tsx';
import _38 from '../../output/svg/c.tsx';
import _39 from '../../output/svg/d.tsx';
import _40 from '../../output/svg/e.tsx';
import _41 from '../../output/svg/f.tsx';
import _42 from '../../output/svg/g.tsx';
import _43 from '../../output/svg/h.tsx';
import _44 from '../../output/svg/i.tsx';
import _45 from '../../output/svg/j.tsx';
import _46 from '../../output/svg/k.tsx';
import _47 from '../../output/svg/l.tsx';
import _48 from '../../output/svg/m.tsx';
import _49 from '../../output/svg/n.tsx';
import _50 from '../../output/svg/o.tsx';
import _51 from '../../output/svg/p.tsx';
import _52 from '../../output/svg/q.tsx';
import _53 from '../../output/svg/r.tsx';
import _54 from '../../output/svg/s.tsx';
import _55 from '../../output/svg/t.tsx';
import _80 from '../../output/svg/U+002a.tsx';
import _81 from '../../output/svg/U+002b.tsx';
import _63 from '../../output/svg/U+002c.tsx';
import _70 from '../../output/svg/U+002d.tsx';
import _62 from '../../output/svg/U+002e.tsx';
import _73 from '../../output/svg/U+002f.tsx';
import _65 from '../../output/svg/U+003a.tsx';
import _64 from '../../output/svg/U+003b.tsx';
import _83 from '../../output/svg/U+003c.tsx';
import _82 from '../../output/svg/U+003d.tsx';
import _84 from '../../output/svg/U+003e.tsx';
import _67 from '../../output/svg/U+003f.tsx';
import _74 from '../../output/svg/U+005c.tsx';
import _87 from '../../output/svg/U+005e.tsx';
import _88 from '../../output/svg/U+005f.tsx';
import _89 from '../../output/svg/U+007c.tsx';
import _85 from '../../output/svg/U+007e.tsx';
import _66 from '../../output/svg/U+0021.tsx';
import _69 from '../../output/svg/U+0022.tsx';
import _76 from '../../output/svg/U+0023.tsx';
import _77 from '../../output/svg/U+0024.tsx';
import _78 from '../../output/svg/U+0025.tsx';
import _79 from '../../output/svg/U+0026.tsx';
import _68 from '../../output/svg/U+0027.tsx';
import _71 from '../../output/svg/U+0028.tsx';
import _72 from '../../output/svg/U+0029.tsx';
import _75 from '../../output/svg/U+0040.tsx';
import _86 from '../../output/svg/U+0060.tsx';
import _56 from '../../output/svg/u.tsx';
import _10 from '../../output/svg/upper_A.tsx';
import _11 from '../../output/svg/upper_B.tsx';
import _12 from '../../output/svg/upper_C.tsx';
import _13 from '../../output/svg/upper_D.tsx';
import _14 from '../../output/svg/upper_E.tsx';
import _15 from '../../output/svg/upper_F.tsx';
import _16 from '../../output/svg/upper_G.tsx';
import _17 from '../../output/svg/upper_H.tsx';
import _18 from '../../output/svg/upper_I.tsx';
import _19 from '../../output/svg/upper_J.tsx';
import _20 from '../../output/svg/upper_K.tsx';
import _21 from '../../output/svg/upper_L.tsx';
import _22 from '../../output/svg/upper_M.tsx';
import _23 from '../../output/svg/upper_N.tsx';
import _24 from '../../output/svg/upper_O.tsx';
import _25 from '../../output/svg/upper_P.tsx';
import _26 from '../../output/svg/upper_Q.tsx';
import _27 from '../../output/svg/upper_R.tsx';
import _28 from '../../output/svg/upper_S.tsx';
import _29 from '../../output/svg/upper_T.tsx';
import _30 from '../../output/svg/upper_U.tsx';
import _31 from '../../output/svg/upper_V.tsx';
import _32 from '../../output/svg/upper_W.tsx';
import _33 from '../../output/svg/upper_X.tsx';
import _34 from '../../output/svg/upper_Y.tsx';
import _35 from '../../output/svg/upper_Z.tsx';
import _57 from '../../output/svg/v.tsx';
import _58 from '../../output/svg/w.tsx';
import _59 from '../../output/svg/x.tsx';
import _60 from '../../output/svg/y.tsx';
import _61 from '../../output/svg/z.tsx';

export const glyphs: Record<string, SvgComponent> = {
  '0': _0,
  '1': _1,
  '2': _2,
  '3': _3,
  '4': _4,
  '5': _5,
  '6': _6,
  '7': _7,
  '8': _8,
  '9': _9,
  A: _10,
  B: _11,
  C: _12,
  D: _13,
  E: _14,
  F: _15,
  G: _16,
  H: _17,
  I: _18,
  J: _19,
  K: _20,
  L: _21,
  M: _22,
  N: _23,
  O: _24,
  P: _25,
  Q: _26,
  R: _27,
  S: _28,
  T: _29,
  U: _30,
  V: _31,
  W: _32,
  X: _33,
  Y: _34,
  Z: _35,
  a: _36,
  b: _37,
  c: _38,
  d: _39,
  e: _40,
  f: _41,
  g: _42,
  h: _43,
  i: _44,
  j: _45,
  k: _46,
  l: _47,
  m: _48,
  n: _49,
  o: _50,
  p: _51,
  q: _52,
  r: _53,
  s: _54,
  t: _55,
  u: _56,
  v: _57,
  w: _58,
  x: _59,
  y: _60,
  z: _61,
  '.': _62,
  ',': _63,
  ';': _64,
  ':': _65,
  '!': _66,
  '?': _67,
  "'": _68,
  '"': _69,
  '-': _70,
  '(': _71,
  ')': _72,
  '/': _73,
  '\\': _74,
  '@': _75,
  '#': _76,
  $: _77,
  '%': _78,
  '&': _79,
  '*': _80,
  '+': _81,
  '=': _82,
  '<': _83,
  '>': _84,
  '~': _85,
  '`': _86,
  '^': _87,
  _: _88,
  '|': _89,
};

export const glyphTimings: Record<string, number> = {
  '0': 0.561,
  '1': 0.28,
  '2': 0.356,
  '3': 0.51,
  '4': 0.488,
  '5': 0.319,
  '6': 0.419,
  '7': 0.491,
  '8': 0.523,
  '9': 0.51,
  A: 0.705,
  B: 0.824,
  C: 0.461,
  D: 0.804,
  E: 0.681,
  F: 0.726,
  G: 0.507,
  H: 0.893,
  I: 0.712,
  J: 0.37,
  K: 0.68,
  L: 0.323,
  M: 0.98,
  N: 0.823,
  O: 0.546,
  P: 0.488,
  Q: 0.678,
  R: 0.655,
  S: 0.509,
  T: 0.503,
  U: 0.507,
  V: 0.484,
  W: 0.984,
  X: 0.662,
  Y: 0.538,
  Z: 0.502,
  a: 0.343,
  b: 0.559,
  c: 0.264,
  d: 0.575,
  e: 0.295,
  f: 0.503,
  g: 0.407,
  h: 0.525,
  i: 0.246,
  j: 0.415,
  k: 0.554,
  l: 0.207,
  m: 0.718,
  n: 0.411,
  o: 0.275,
  p: 0.608,
  q: 0.376,
  r: 0.36,
  s: 0.273,
  t: 0.469,
  u: 0.415,
  v: 0.178,
  w: 0.47,
  x: 0.545,
  y: 0.497,
  z: 0.301,
  '.': 0.01,
  ',': 0.069,
  ';': 0.226,
  ':': 0.163,
  '!': 0.178,
  '?': 0.284,
  "'": 0.062,
  '"': 0.274,
  '-': 0.07,
  '(': 0.33,
  ')': 0.302,
  '/': 0.287,
  '\\': 0.257,
  '@': 0.725,
  '#': 1.377,
  $: 0.804,
  '%': 1.019,
  '&': 0.761,
  '*': 0.57,
  '+': 0.362,
  '=': 0.325,
  '<': 0.371,
  '>': 0.379,
  '~': 0.131,
  '`': 0.039,
  '^': 0.169,
  _: 0.106,
  '|': 0.295,
};
